version: '3.3'
services:
    portainer-ce:
        image: 'portainer/portainer-ce:latest'
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        environment:
          - PUID=1003           #Change this if different for appuser
          - PGID=100            #Change this if different
          - TZ=Asia/Taipei  #Change timezone if different
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'CHANGE_TO_COMPOSE_DATA_PATH/portainer/portainer_data:/data'