version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_DB: postgres      
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Taipei  #Change timezone if different
    volumes:
       - CHANGE_TO_COMPOSE_DATA_PATH/odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      TZ: Asia/Taipei  #Change timezone if different
    volumes:
       - CHANGE_TO_COMPOSE_DATA_PATH/pgadmin:/var/lib/pgadmin
    user: "${UID}:${GID}"
    ports:
      - "8080:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

#volumes:
#    odoo-db-data:
#    pgadmin:
