#https://dbt3ch.com/books/prometheus-grafana-dashboard/page/prometheusyml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.68.127:9090'] ## IP Address of the localhost. Match the port to your container port
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['192.168.68.127:9100'] ## IP Address of the localhost