# https://qiita.com/sammrai/items/0c329ac7aa8b100b66a8#%E3%82%B5%E3%83%BC%E3%83%93%E3%82%B9%E3%81%AE%E8%B5%B7%E5%8B%95

version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - grafana_network
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=grafana
      - DOCKER_INFLUXDB_INIT_PASSWORD=grafana123123
      - DOCKER_INFLUXDB_INIT_ORG=philphoenix.com
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-secret-auth-token
    volumes:
      - ./data/influxdb:/var/lib/influxdb2 
      - ./data/influxdb-config:/etc/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - grafana_network
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
  
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    depends_on:
      - influxdb

networks:
  grafana_network: