# https://qiita.com/robozushi10/items/a0e8b3de1b9a9628f751#docker-composeyml  

version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      grafana_network:
        ipv4_address: ${MACVLAN_HOST3_GRAFANA_IP} #Change, your nextcloud ipaddress
      backend-network:
    #ports:
    #  - '3000:3000'
    # エラー「GF_PATHS_DATA='/var/lib/grafana' is not writable」の対策として、UID = 472 にする
    # https://amemo.hatenablog.jp/entry/2018/07/20/212116
    # https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later
    #user: '472:0'
    environment:
      - PUID=${APPUSER_PUID}               #Change to your user PUID
      - PGID=${APPUSER_PGID}               #Change to your user PGID
      - TZ=${TIME_ZONE_VALUE}      #Change to your timezone  
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb

  fluentd:
    image: fluent/fluentd:v1.13-1
    container_name: fluentd
    build: assets/fluentd/.
    #user: '1000:1000'
    environment:
      - PUID=${APPUSER_PUID}               #Change to your user PUID
      - PGID=${APPUSER_PGID}               #Change to your user PGID
      - TZ=${TIME_ZONE_VALUE}      #Change to your timezone  
    restart: always
    command: >
      /usr/bin/fluentd -c /fluentd/etc/fluent.conf -v
    networks:
      backend-network:  
    ports:
      - "127.0.0.1:44224:44224"
      - "127.0.0.1:44224:44224/udp"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/fluentd/log:/fluentd/log
      - CHANGE_TO_COMPOSE_DATA_PATH/fluentd/etc:/fluentd/etc

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    networks:
      backend-network:
    ports:
      - '8086:8086'
    environment:
      - PUID=${APPUSER_PUID}               #Change to your user PUID
      - PGID=${APPUSER_PGID}               #Change to your user PGID
      - TZ=${TIME_ZONE_VALUE}      #Change to your timezone                  
      - INFLUXDB_DB=grafana
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=grafana
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_ORG=philphoenix.com
      - INFLUXDB_BUCKET=my-bucket
      - INFLUXDB_RETENTION=1w
      - INFLUXDB_ADMIN_TOKEN=super-secret-auth-token
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/influxdb2:/var/lib/influxdb2 
      - CHANGE_TO_COMPOSE_DATA_PATH/influxdb2-config:/etc/influxdb2

volumes:
    grafana-data:
    influxdb2-data:
    fluentd-data:
    
networks:
  backend-network:
    name: influxdb-backend-network
  grafana_network:
    name: macvlan-network
    external: true